---

- name: Cat the resolv.conf file
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Cat the resolv.conf file
      ansible.builtin.command:
        cat /etc/resolv.conf

...
