---

- name: Check DNS servers in resolv.conf
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check resolv.conf exists
      ansible.builtin.stat:
        path: /etc/resolv.conf
      register: resolv_conf
    - name: Check nameservers list in resolv.conf
      ansible.builtin.debug:
        msg: "{{ contents }}"
      vars:
        contents: "{{ lookup('file', '/etc/resolv.conf') | regex_findall('\\s*nameserver\\s*(.*)') }}"
      when: resolv_conf.stat.exists
