---
- name: Install CLI Tools
  hosts: ubuntu_vms

  vars_files:
    - vars/cli_tools_vars.yaml

  tasks:
    - name: Install CLI Tools
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      become: yes
      with_items: "{{ cli_tools }}"